print("Enter a number :")
num1 = input()
print("Enter another number :")
num2 = input()
Sum=int(num1)+ int(num2)
print("Sum of two numbers is ", Sum)
print("Difference of two numbers is ", int(num1)-int(num2))
print("Product of two numbers is ", int(num1)*int(num2))
print("Quotient of two numbers is ", int(num1)/int(num2))
print("Modulus of two numbers is ", int(num1)%int(num2))
print("Integral divison of two numbers is ", int(num1)//int(num2))
print("number one raised to the power of number 2 is ", int(num1)**int(num2))
